// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrbwnahotvrslmokhhgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyYnduYWhvdHZyc2xtb2toaGd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3ODQ5MTAsImV4cCI6MjA2MDM2MDkxMH0.cVkBMEwi3EbUwJBWZ5lOfG6weXdEzW_V8Un6GZENRbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);